### ISSUE TITLE
Publish package to NPM registry

### ISSUE THREAD

**Issue by bclermont** [pancakeswap/pancakeswap-sdk-v2#5]
There is [~100 published package of pancakeswap sdk on NPM](https://www.npmjs.com/search?q=pancakeswap)

I trust none of them, but [this one](https://www.npmjs.com/package/@pancakeswap/pancake-swap-lib). But it's for v1. Can we have a v2.2.0 release?

**Comment by ChefKai** [comment]
Hello, PancakeSwap SDK v2: https://www.npmjs.com/package/@pancakeswap-libs/sdk-v2
